volumes:
  my_db:
  redis: {}

services:
  my_app:
    build:
      context: .
      target: runner
    container_name: fast_api_base
    # restart: on-failure
    ports:
      - "8080:8000"
    expose:
      - "8000"
    environment:
      HAPPY_FUN_TIMES: "now"
      PYTHONPATH: ./app/
      DB_USER_MIG: user
      DB_PASSWORD_MIG: password
      DB_HOST: example_db
      DB_PORT: 3306
      DB_NAME: fast_api_base
      CELERY_BROKER_URL: "redis://example_redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://example_redis:6379/1"
    volumes:
      - ./app/:/app/app
    depends_on:
      - "db"
      - "redis"
    links:
      - "db:example_db"
      - "redis:example_redis"
  db:
    image: mysql/mysql-server:5.7
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: 'fast_api_base'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'super_password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '53306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my_db:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: example_redis
    volumes:
      - "redis:/data"
    ports:
      - '6379:6379'
    expose:
      - '6379'
